#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "util.h"
#include "hashfn.h"

int main(int argc, char *argv[]){

    //if a different number of command line arguments are provided, prints the stderr and returns
    if(argc != 3){
        fprintf( stderr, "Usage: %s filename.kv ‘search term’\n", argv[0]);
        return -1;
    }
    else{

        FILE *kv;
        FILE *vhs;

        //creates a new variable for the vhs file name
        int lengthName = strlen(argv[1]) - 3;
        char *kvFile = (char *)malloc(sizeof(char) * (strlen(argv[1]) + 1));
        char *fileName = (char *)malloc(sizeof(char) * (lengthName + 1));
        strcpy(kvFile, argv[1]);
        strncpy(fileName, kvFile, lengthName);
        fileName[lengthName] = '\0';
        char *vhsFile = (char *)malloc(sizeof(char) * (lengthName + 5));
        char vhsEx[5] = ".vhs\0";
        strcpy(vhsFile, fileName);
        strcat(vhsFile, vhsEx);

        kv = fopen(argv[1], "rb");
        vhs = fopen(vhsFile, "rb");

        //begins search for the given search term beginning at the index computed by the hashfn function
        int vhsCap = get_capacity(vhs);
        fseek(vhs, 0, SEEK_SET);
        int hashIndex = hashfn(argv[2], vhsCap - 1);
        printf("%d\n", hashIndex);
        int searchFound = 0;
        int id;
        int len = strlen(argv[2]);
        char val[STRLEN];
        char key[STRLEN];

        for(int index = hashIndex; index < vhsCap; index++){

            //uses the hash value as the hash for the read_index function
            read_index(vhs, index, &id);

            //check the return value of read_key with the value generated by read_index
            read_key(kv, id, key);

            //if the key value retreived from the kv file matches the search term
            if(strncmp(key, argv[2], len) == 0){
                //then, the read_value function is used to retreive the corresponding value from the kv file
                read_val(kv, id, val);
                
                //prints the value followed by '\n'
                printf("%s\n", val);
                searchFound = 1;
                break;
            }

            //loop back to zero when the end of the file is hit and keep looping until the entire table has been searched
            else if(index == vhsCap - 1){
                index = -1;
            }
            //if the key value doesn't match the search term, continue through the hash table
            else if(index == hashIndex - 1){
                break;
            }
        }

        if(searchFound == 0){
            //if the search term is not found, error message is printed
            printf("NOT FOUND\n");
        }

        //frees any allocated memory and closes all files
        fclose(kv);
        fclose(vhs);
        free(kvFile);
        free(fileName);
        free(vhsFile);
    }

    return 0;
}